myproject/myapp/urls.py
from django.urls import path,include
from . import views

app_name='myapp'

urlpatterns = [
    path('',views.Index.as_view(),name='index'),
    path('post_create',views.PostCreate.as_view(),name='post_page'),
    path('post_detail/<int:pk>',views.PostDetail.as_view(),name='post_detail'),
    path('post_update/<int:pk>',views.PostUpdate.as_view(),name='post_update'),
    path('post_delete/<int:pk>',views.PostDelete.as_view(),name='post_delete'),
]

myproject/myproject/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('myapp.urls')),
]

myproject/myapp/models.py
from django.db import models

#今日はいい天気
class Post(models.Model):
    title = models.CharField('タイトル',max_length=50)
    content = models.TextField('内容',max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

myproject/myapp/views.py
from multiprocessing import context
from django.shortcuts import render,resolve_url
from django.http import HttpResponse
from django.views.generic import TemplateView,CreateView
from .models import Post
from django.urls import reverse_lazy
from .form import PostForm
from django.views.generic import TemplateView,CreateView,DetailView,UpdateView,DeleteView


class Index(TemplateView):
    template_name='myapp/index.html'

    def get_context_data(self,*args, **kwargs) :
        context = super().get_context_data
        post_list= Post.objects.all().order_by('-created_at')
        context={'post_list':post_list,}
        return context


class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('myapp:index')


class PostDetail (DetailView):
    model=Post


class PostUpdate(UpdateView):
    model=Post
    form_class =PostForm
    def get_success_url(self):
        return resolve_url('myapp:post_detail',pk=self.kwargs['pk'])

class PostDelete(DeleteView):
    model=Post
    def get_success_url(self):
        return resolve_url('myapp:index')

myproject/myapp/templates/myapp/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>自己紹介</title>
  <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.css" rel="stylesheet" />
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/5.0.0/mdb.min.js"></script>
</head>
<body>
  <div class="container">
    <!-- Content here -->

  
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
      <!-- container -->
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="/">Momoko</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/admin" target="_blank">かんりがめん</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:post_page' %}">しんきとうこう</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Navbar -->
    {% block content %}
    {% endblock %}


</div>
<!-- container -->
</body>

</html>

myproject/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block content %}


<!-- Jumbotron -->
<div class="p-5 text-center bg-light">
  <h1 class="mb-3">Heading</h1>
  <h4 class="mb-3">Subheading</h4>
  <a class="btn btn-primary" href="" role="button">Call to action</a>
</div>
<!-- Jumbotron -->

{% for item in post_list %}
<!-- cards -->
<div class="row row-cols-1 row-cols-md-2 g-4">
  <div class="col">
    <div class="card">
      <img src="https://mdbcdn.b-cdn.net/img/new/standard/city/041.webp" class="card-img-top"
        alt="Hollywood Sign on The Hill" />
      <div class="card-body">
        <h5 class="card-title">{{item.title}}</h5>
        <p class="card-text">
          テスト中でーす
        </p>
        <a href="{% url 'myapp:post_detail' item.id%}" type="submit" class="btn btn-success" >アクセス</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

<!-- cards -->
{% endblock %}

myproject/myapp/templates/myapp/post_confirm_delete.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2>Postを削除</h2>
        <br>
        <div class='alert alert-danger'role="alert">
            <form method="post">
                {% csrf_token %}
                <p>以下の内容を本当に本当に削除しますか？</p>
                <input type="submit" class="btn btn-outline-danger" value="削除する">
            </form>
        </div>

        <br>
        <p>タイトル</p>
        {{object.title}}
        <hr>
        <p>内容</p>
        {{object.content}}
        
    </div>
</div>
{% endblock %}

myproject/myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}
{% block content %}


<div class="row"></div>
<div class="row-cols-md-9"></div>
<div class="card">
    <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/184.webp" class="card-img-top" alt="Fissure in Sandstone"/>
    <div class="card-body">
      <h5 class="card-title">{{object.title}}</h5>
      <p class="card-text">{{object.content}}</p>
      <a href="{% url 'myapp:post_update' object.id %}" class="btn btn-primary">更新</a>
      <a href="{% url 'myapp:post_delete' object.id %}" class="btn btn-danger">削除</a>
    </div>
  </div>


{% endblock %}

myproject/myapp/templates/myapp/post_form.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="row">
    <div class="col-md-9">
        <br>
        <h2>登録ページ</h2>
        <br>


        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>タイトル</label>
                {{form.title }}
            </div>
            <br>
            <div class="form-group">
                <label>内容</label>
                {{form.content}}
            </div>
            <br>
            <button type="submit" class="btn btn-success">保存</button>

        </form>
    </div>
</div>
{% endblock %}